#### Numpy
NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

In [ ]:
#pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [8]:
import numpy as np

## create array using numpy
##create a 1D array
arr1=np.array([1,2,3,4,5,8,9 ]) # calling the array function from NumPy module to convert the list into array.
print(arr1)
print(type(arr1))
print(arr1.shape) ## shape attribute defines the size of the array:
# For 1D array → it shows the number of elements
# For 2D array → it shows (rows, columns) like (2,3)

[1 2 3 4 5 8 9]
<class 'numpy.ndarray'>
(7,)


In [11]:
## 1 d array
arr2=np.array([1,2,3,4,5])
arr2.reshape(5,1)  ## 5 row and 1 columns
# reshape() changes the shape of the array
# here it converts the array into 5 row and 1 columns

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [17]:
arr2=np.array([[1,7,6,2,3,4,5]])
arr1=np.array([1,2,3,4,4,8,7,5])
print(arr2.shape) # It shows the rows and columns of 2-D array.
print(arr1.shape) # It shows only the number of elements of 1-D array.

(1, 7)
(8,)


In [ ]:
## 2d array
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape) # 2 rows and 5 columns

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [18]:
np.arange(0,10,2).reshape(5,1)
# arange() creates numbers from 0 to 10 with step 2 → [0,2,4,6,8]
# reshape(5,1) changes the array shape to 5 rows and 1 column

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [20]:
np.ones((3,4))
# ones() function creates an array filled with 1
# here it creates a 2D array with 3 rows and 4 columns

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
## identity matrix
np.eye(3)
# eye() creates an identity matrix
# here it creates a 3×3 matrix with 1s on the diagonal and 0s elsewhere

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

* arr.ndim

ndim attribute defines the number of dimensions of the array

* arr.dtype

dtype attribute defines the data type of the array elements

* arr.itemsize

itemsize attribute defines the size (in bytes) of each element in the array

In [18]:
## Attributes of Numpy Array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape)  # Output: (2, 3)
print("Number of dimensions:", arr.ndim)  # Output: 2
print("Size (number of elements):", arr.size)  # Output: 6
print("Data type:", arr.dtype)  # Output: int32 (may vary based on platform)
print("Item size (in bytes):", arr.itemsize)  # Output: 8 (may vary based on platform)


Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int32
Item size (in bytes): 4


In [19]:
### Numpy Vectorized Operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

### Element Wise addition
print("Addition:", arr1+arr2)

## Element Wise Substraction
print("Substraction:", arr1-arr2)

# Element-wise multiplication
print("Multiplication:", arr1 * arr2)

# Element-wise division
print("Division:", arr1 / arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [ ]:
## Universal Function
arr=np.array([2,3,4,5,6])
## square root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr)) # exp() returns the exponential value (e^x) of each element in the array

## Sine
print(np.sin(arr)) # sin() returns the sine value of each element in the array . # We can also use other trigonometric functions like cos(), tan(), etc. to get their values.

## natural log
print(np.log(arr)) # log() returns the natural logarithm (log base e) of each element in the array

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [24]:
## array slicing and Indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n", arr)
print(arr.shape) # 3 rows & 4 columns



Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [26]:
print(arr[1:,1:3]) # 1:  → rows start from index 1 to the last row
# 1:3 → columns from index 1 up to (but not including) 3 → means column 1 and 2

[[ 6  7]
 [10 11]]


In [32]:
print(arr[0][0])
print(arr[0:2,2:])

1
[[3 4]
 [7 8]]


In [27]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [ ]:
## Modify array elements
arr[0,0]=100 # modify the element at (0,0) 
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [28]:
arr[1:]=100  # modifying the element from 1 row
print(arr)

[[  1   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [38]:
### statistical concepts--Normalization
##to have a mean of 0 and standard deviation of 1
data = np.array([1, 2, 3, 4, 5])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)



Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [39]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)



Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [30]:
## Logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)]
# filters elements between 5 and 8 from the NumPy array
# since the input 'data' is a NumPy array, the filtered result is also returned as a NumPy array

array([5, 6, 7, 8])